"""Define and filelist generators (v0.5, SPEC §16).

Generates .vh header files and .f filelists from parsed defines.
"""

from __future__ import annotations

from excel2design.core.models import Define


def generate_vh(defines: list[Define], module_name: str) -> str:
    """Generate a Verilog header file with `define macros.

    Format: one `define per line, left-aligned with consistent spacing.
    """
    if not defines:
        return ""

    # Calculate max name length for alignment
    max_name = max(len(d.name) for d in defines)

    lines = [
        "// =====================================================",
        f"// {module_name}.vh — generated by excel2design v0.5",
        "// =====================================================",
    ]

    for d in defines:
        if d.value:
            lines.append(f"`define {d.name:<{max_name}} {d.value}")
        else:
            lines.append(f"`define {d.name}")

    return "\n".join(lines) + "\n"


def generate_f(module_names: list[str], project_name: str) -> str:
    """Generate a .f filelist for simulation tools.

    Lists rtl/<module>.v in hierarchical order.
    """
    if not module_names:
        return ""

    lines = [
        "// " + "=" * 40,
        f"// {project_name}.f — generated by excel2design v0.5",
        "// " + "=" * 40,
    ]

    for name in module_names:
        # Strip hierarchy prefix for file names
        short_name = name.rsplit(".", 1)[-1] if "." in name else name
        lines.append(f"rtl/{short_name}.v")

    return "\n".join(lines) + "\n"
